import pandas as pd
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.client_credential import ClientCredential

"""
perGameListAPIRecordUploader.py
Written By: Jack Piotrowski
Description: Uploads a PerGame stats csv with individual game stats to the PerGame List on SharePoint. Right now,
            only auburn game individual stats should be uploaded to the PerGame List (our scope).
Future Development: Modify the file to allow it to go through a directory of csvs that include single game calculated statistics
                    from Auburn games. This will allow all new Auburn games from a week to be uploaded to the PerGame List.
"""

# SharePoint Credentials (DO NOT SHARE)
site_url = "https://tigermailauburn.sharepoint.com/sites/BaseballStatsRaw"
client_id =
client_secret =

# Read in csv as dataframe
file_path = input("Enter the path to the player_stats csv file: ")
df = pd.read_csv(file_path)  #Feed in PerGame stats generated by playerStatsConverter.py

#Authentication
credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(credentials)
#Reference the Per-Game List on Sharepoint
sharepoint_list = ctx.web.lists.get_by_title('PerGame')

#Convert the dataframe into a dictionary
#Allows each csv record/row to be accessed individually, then uploaded
data = df.to_dict('records')

# Mapping the Column headers in the generated Per-game CSVs to their associated field name within the SharePoint API
# The "Title" matches the "Title" column in the Per-Game List on the Baseball Stats Raw site.
# Every field after Title is just field_x, incrementing for each field after
# It follows the columns in the Per-Game csv.
mapped_data = []
for item in data:
    mapped_item = {
        'Title': item['GameID'],
        'field_1' : item['PlayerName'],
        'field_2': item['W-L'],
        'field_3': item['EarnedRuns'],

        'field_4': item['InningsPitched'],
        'field_5': item['TBF'],
        'field_6': item['ERA'],
        'field_7': item['TotalPitches'],
        'field_8': item['Strikes'],
        'field_9': item['Balls'],
        'field_10': item['FoulsAfter2Strikes'],
        'field_11': item['HitBatters'],

        'field_12': item['Strike%'],
        'field_13': item['Ball%'],
        'field_14': item['FirstPitchStrikes'],
        'field_15': item['FirstPitchBalls'],
        'field_16': item['FirstPitchStrike%'],
        'field_17': item['FirstPitchBall%'],
        'field_18': item['First2of3StrikesOrInPlay'],
        'field_19': item['AtBatEfficiency'],

        'field_20': item['AtBatEfficiency%'],
        'field_21': item['Strikeouts'],
        'field_22': item['Walks'],
        'field_23': item['HomeRuns'],
        'field_24': item['Strikeout%'],
        'field_25': item['Walk%'],
        'field_26': item['FIP'],
        'field_27': item['Swings'],

        'field_28': item['Whiffs'],
        'field_29': item['Whiff%'],
        'field_30': item['CalledStrikes'],
        'field_31': item['CSW%'],
        'field_32': item['InZoneSwings'],
        'field_33': item['InZoneWhiffs'],
        'field_34': item['IZWhiff%'],
        'field_35': item['OutZoneSwings'],

        'field_36': item['OutZonePitches'],
        'field_37': item['Chase%'],

        'field_38': item['FBnVAA'],
        'field_39': item['FBVAAUpper'],
        'field_40': item['FBVAAMid'],
        'field_41': item['FBVAALower'],
        'field_42': item['Fastballs'],
        'field_43': item['FastballAvgVelo'],

        'field_44': item['FastballMaxVelo'],
        'field_45': item['FastballMinVelo'],
        'field_46': item['FastballAvgIVB'],
        'field_47': item['FastballMaxIVB'],
        'field_48': item['FastballMinIVB'],
        'field_49': item['FastballAvgHB'],
        'field_50': item['FastballMaxHB'],
        'field_51': item['FastballMinHB'],

        'field_52': item['FastballAvgSpin'],
        'field_53': item['FastballMaxSpin'],
        'field_54': item['FastballMinSpin'],
        'field_55': item['FastballInZone'],
        'field_56': item['FastballInZone%'],
        'field_57': item['FastballAvgReleaseHeight'],
        'field_58': item['FastballAvgExtension'],
        'field_59': item['Cutters'],

        'field_60': item['CutterAvgVelo'],
        'field_61': item['CutterMaxVelo'],
        'field_62': item['CutterMinVelo'],
        'field_63': item['CutterAvgIVB'],
        'field_64': item['CutterMaxIVB'],
        'field_65': item['CutterMinIVB'],
        'field_66': item['CutterAvgHB'],
        'field_67': item['CutterMaxHB'],

        'field_68': item['CutterMinHB'],
        'field_69': item['CutterAvgSpin'],
        'field_70': item['CutterMaxSpin'],
        'field_71': item['CutterMinSpin'],
        'field_72': item['CutterInZone'],
        'field_73': item['CutterInZone%'],
        'field_74': item['CutterAvgReleaseHeight'],
        'field_75': item['CutterAvgExtension'],

        'field_76': item['Sinkers'],
        'field_77': item['SinkerAvgVelo'],
        'field_78': item['SinkerMaxVelo'],
        'field_79': item['SinkerMinVelo'],
        'field_80': item['SinkerAvgIVB'],
        'field_81': item['SinkerMaxIVB'],
        'field_82': item['SinkerMinIVB'],
        'field_83': item['SinkerAvgHB'],

        'field_84': item['SinkerMaxHB'],
        'field_85': item['SinkerMinHB'],
        'field_86': item['SinkerAvgSpin'],
        'field_87': item['SinkerMaxSpin'],
        'field_88': item['SinkerMinSpin'],
        'field_89': item['SinkerInZone'],
        'field_90': item['SinkerInZone%'],
        'field_91': item['SinkerAvgReleaseHeight'],

        'field_92': item['SinkerAvgExtension'],
        'field_93': item['Sliders'],
        'field_94': item['SliderAvgVelo'],
        'field_95': item['SliderMaxVelo'],
        'field_96': item['SliderMinVelo'],
        'field_97': item['SliderAvgIVB'],
        'field_98': item['SliderMaxIVB'],
        'field_99': item['SliderMinIVB'],

        'field_100': item['SliderAvgHB'],
        'field_101': item['SliderMaxHB'],
        'field_102': item['SliderMinHB'],
        'field_103': item['SliderAvgSpin'],
        'field_104': item['SliderMaxSpin'],
        'field_105': item['SliderMinSpin'],
        'field_106': item['SliderInZone'],
        'field_107': item['SliderInZone%'],

        'field_108': item['SliderAvgReleaseHeight'],
        'field_109': item['SliderAvgExtension'],
        'field_110': item['PA'],
        'field_111': item['AB'],
        'field_112': item['H'],
        'field_113': item['TB'],
        'field_114': item['1B'],
        'field_115': item['2B'],

        'field_116': item['3B'],
        'field_117': item['HR'],
        'field_118': item['RBI'],
        'field_119': item['BB'],
        'field_120': item['K'],
        'field_121': item['HBP'],
        'field_122': item['SF'],
        'field_123': item['SH'],

        'field_124': item['GDP'],
        'field_125': item['AVG'],
        'field_126': item['BB%'],
        'field_127': item['K%'],
        'field_128': item['OBP'],
        'field_129': item['SLG'],
        'field_130': item['OPS'],
        'field_131': item['ISO'],

        'field_132': item['BABIP'],
        'field_133': item['wOBA'],
        'field_134': item['AvgExitVelocity'],
        'field_135': item['AvgLaunchAngle']

    }
    mapped_data.append(mapped_item)

# Add the new records to the PerGame List on SharePoint
# Excutes the query to officially upload each row/record
for item in mapped_data:
    sharepoint_list.add_item(item)
    ctx.execute_query()

